[package]
name = "jsonarchive"
version = "0.1.0"
authors = ["Datalust <hello@datalust.co>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"

[dependencies.chrono]
version = "0.4"
features = ["serde"]
